services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    healthcheck:
      test: ["CMD-SHELL", "apt-get update && apt-get install -y curl && curl -f http://localhost:11434/ && apt-get clean && rm -rf /var/lib/apt/lists/*"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    ports:
      - "11434:11434"
    expose:
      - '11434'
    volumes:
      - ollama:/root/.ollama
    networks:
      - lmdsgen-backend

networks:
  lmdsgen-backend:

volumes:
  ollama:
