services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: lazyollama/web:latest
    container_name: lazyollama-web
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4040"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "4040:4040"
    expose:
      - '4040'

